### ISSUE TITLE
Personal project use

### ISSUE THREAD

**Issue by GreenMan36** [Neocky/choco-runner#1]
I'm currently working on a project myself to help aid people move existing programs to chocolatey.
It checks the winreg for installed programs and allows the user to quickly search packages to add to a list. 
It would then install this list.
There's some added goodness like the option of auto converting a verified list of programs in the future; along with loading other people's program list and package lists. Like a quick backup so you can get on a new install faster. (My own use case)
![image](https://user-images.githubusercontent.com/5887406/163733091-6188d38f-4a86-4ce0-b665-70f0419e3df8.png)

The question is; would you mind if I used parts of your script or just ran the script itself in my project? 

PS; its made with Python and TK.

**Comment by Neocky** [comment]
Hey @GreenMan36,
feel free to use this project/parts of this project for your own project. 
Just make sure you comply with the license and give appropriate License and copyright notice. 😃 
Check the license in full detail [here](https://github.com/Neocky/choco-runner/blob/main/LICENSE).

Cheers!
